import typer
import logging
from pathlib import Path

from autosub.pipeline.transcribe import main as transcribe_main
from autosub.pipeline.format import main as format_module
from autosub.pipeline.postprocess import main as postprocess_module
from autosub.pipeline.translate import main as translate_module
from autosub.core.profile import load_unified_profile

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s:%(levelname)s:%(name)s: %(message)s"
)
logger = logging.getLogger(__name__)

app = typer.Typer(help="AutoSub CLI for Japanese subtitle generation and translation")


@app.callback()
def main():
    pass


@app.command()
def transcribe(
    video_path: Path = typer.Argument(
        ..., help="Path to the input video or audio file"
    ),
    output: Path = typer.Option(
        Path("transcript.json"),
        "--out",
        "-o",
        help="Path to save the output JSON transcript",
    ),
    language: str = typer.Option(
        "ja-JP",
        "--language",
        "-l",
        help="Language code for transcription (e.g. ja-JP, en-US)",
    ),
    vocab: list[str] = typer.Option(
        None,
        "--vocab",
        "-v",
        help="Custom context terminology to increase probability of recognition (can be passed multiple times).",
    ),
    profile: str = typer.Option(
        None,
        "--profile",
        help="Profile name to load transcription vocabulary hints.",
    ),
    speakers: int = typer.Option(
        None,
        "--speakers",
        "-s",
        help="Reserved for future diarization work. Ignored by the current single-speaker pipeline.",
    ),
    start: str = typer.Option(
        None,
        "--start",
        help="Start time for transcription (e.g. 00:01:00 or 60).",
    ),
    end: str = typer.Option(
        None,
        "--end",
        help="End time for transcription (e.g. 00:04:00 or 240).",
    ),
):
    """
    Extracts audio and transcribes Japanese speech with Google Cloud Speech-to-Text.
    """
    logger.info(f"Starting transcription pipeline for: {video_path}")

    final_vocab = []
    if profile:
        profile_data = load_unified_profile(profile)
        final_vocab.extend(profile_data["vocab"])
    if vocab:
        final_vocab.extend(vocab)

    if speakers:
        logger.warning(
            "--speakers is currently ignored. The active pipeline is single-speaker only."
        )

    try:
        result = transcribe_main.transcribe(
            video_path,
            output,
            language,
            final_vocab,
            start_time=start,
            end_time=end,
        )
        logger.info(f"Success! Saved {len(result.words)} words to {output}")
    except Exception as e:
        logger.error(f"Error during transcription: {e}")
        raise typer.Exit(code=1)


@app.command()
def format(
    input_transcript: Path = typer.Argument(
        ...,
        help="Path to the input transcript.json file generated by the transcribe command.",
        exists=True,
        dir_okay=False,
    ),
    out: Path = typer.Option(
        None,
        "--out",
        help="Path to save the generated output .ass file (defaults to original.ass in the same directory).",
    ),
    keyframes: Path = typer.Option(
        None, "--keyframes", help="Path to Aegisub keyframes log for snapping."
    ),
    fps: float = typer.Option(
        0.0, "--fps", help="Video FPS, required if --keyframes is used."
    ),
    profile: str = typer.Option(
        None,
        "--profile",
        help="Profile name to load timing and formatting extension configuration.",
    ),
):
    """
    Step 2: Converts a transcript JSON into timed single-lane .ass subtitles.
    """
    if not out:
        out = input_transcript.with_name("original.ass")

    if keyframes and fps <= 0:
        logger.error("--fps is required when --keyframes is provided.")
        raise typer.Exit(code=1)

    timing_config = {}
    extensions_config = {}
    replacements = {}
    if profile:
        profile_data = load_unified_profile(profile)
        timing_config = profile_data.get("timing", {})
        extensions_config = profile_data.get("extensions", {})
        replacements = profile_data.get("replacements", {})

    kf_ms = None
    if keyframes and fps > 0:
        from autosub.pipeline.video.keyframes import parse_aegisub_keyframes

        kf_ms = parse_aegisub_keyframes(keyframes, fps)

    try:
        format_module.format_subtitles(
            input_transcript,
            out,
            keyframes=kf_ms,
            timing_config=timing_config,
            extensions_config=extensions_config,
            replacements=replacements,
        )
    except Exception as e:
        logger.error(f"Error during formatting: {e}")
        raise typer.Exit(code=1)


@app.command()
def translate(
    input_ass: Path = typer.Argument(
        ...,
        help="Path to the original .ass file generated by the format command.",
        exists=True,
        dir_okay=False,
    ),
    out: Path = typer.Option(
        None,
        "--out",
        help="Path to save the translated .ass file (defaults to translated.ass in the same directory).",
    ),
    engine: str = typer.Option(
        "vertex",
        "--engine",
        "-e",
        help="Translation engine to use ('vertex' or 'cloud-v3').",
    ),
    prompt: str = typer.Option(
        None, "--prompt", "-p", help="System prompt to guide the LLM translation."
    ),
    profile: str = typer.Option(
        None,
        "--profile",
        help="Profile name to load translation prompt settings.",
    ),
    target_lang: str = typer.Option("en", "--target", help="Target language code."),
    source_lang: str = typer.Option("ja", "--source", help="Source language code."),
    bilingual: bool = typer.Option(
        False,
        "--bilingual/--replace",
        help="Include original text on top, or replace completely.",
    ),
    chunk: bool = typer.Option(
        False,
        "--chunk/--no-chunk",
        help="Split translation into smaller chunks with retry logic. Useful for long files.",
    ),
    chunk_size: int = typer.Option(
        80,
        "--chunk-size",
        help="Number of subtitle lines per chunk when --chunk is enabled.",
    ),
):
    """
    Step 3: Translates a .ass subtitle file using the configured Translation Engine.
    """
    if not out:
        out = input_ass.with_name("translated.ass")

    final_prompt_parts = []
    if profile:
        profile_data = load_unified_profile(profile)
        final_prompt_parts.extend(profile_data["prompt"])

        if profile_data.get("glossary"):
            glossary_text = "Glossary (Always translate these exact phrases):\n"
            for ja, en in profile_data["glossary"].items():
                glossary_text += f'- "{ja}" -> "{en}"\n'
            final_prompt_parts.append(glossary_text)

    if prompt:
        final_prompt_parts.append(prompt)

    final_prompt = "\n\n".join(final_prompt_parts) if final_prompt_parts else None

    chunk_size = chunk_size if chunk else 0

    try:
        translate_module.translate_subtitles(
            input_ass,
            out,
            engine=engine,
            system_prompt=final_prompt,
            target_lang=target_lang,
            source_lang=source_lang,
            bilingual=bilingual,
            chunk_size=chunk_size,
        )
    except Exception as e:
        logger.error(f"Error during translation: {e}")
        raise typer.Exit(code=1)


@app.command()
def postprocess(
    input_ass: Path = typer.Argument(
        ...,
        help="Path to the translated .ass file generated by the translate command.",
        exists=True,
        dir_okay=False,
    ),
    out: Path = typer.Option(
        None,
        "--out",
        help="Path to save the postprocessed .ass file (defaults to overwriting the input file).",
    ),
    profile: str = typer.Option(
        None,
        "--profile",
        help="Profile name to load postprocessing extension configuration.",
    ),
    bilingual: bool = typer.Option(
        False,
        "--bilingual/--replace",
        help="Treat the input as bilingual stacked subtitles, or translated-only subtitles.",
    ),
):
    """
    Step 4: Applies optional post-translation subtitle cleanup and editorial transforms.
    """
    final_extensions = {}
    if profile:
        profile_data = load_unified_profile(profile)
        final_extensions = profile_data.get("extensions", {})

    try:
        postprocess_module.postprocess_subtitles(
            input_ass,
            output_ass_path=out,
            extensions_config=final_extensions,
            bilingual=bilingual,
        )
    except Exception as e:
        logger.error(f"Error during postprocessing: {e}")
        raise typer.Exit(code=1)


@app.command()
def run(
    video_path: Path = typer.Argument(
        ..., help="Path to the input video or audio file"
    ),
    out_dir: Path = typer.Option(
        None,
        "--out-dir",
        help="Directory to save generated files. Defaults to the input video's directory.",
    ),
    language: str = typer.Option(
        "ja-JP", "--language", "-l", help="Language code for transcription (e.g. ja-JP)"
    ),
    profile: str = typer.Option(
        None,
        "--profile",
        help="Profile name to load vocabulary, timing, prompt, and extension settings.",
    ),
    vocab: list[str] = typer.Option(
        None, "--vocab", "-v", help="Custom transcription hints."
    ),
    engine: str = typer.Option(
        "vertex", "--engine", "-e", help="Translation engine ('vertex' or 'cloud-v3')."
    ),
    prompt: str = typer.Option(
        None, "--prompt", "-p", help="System prompt to guide the LLM translation."
    ),
    target_lang: str = typer.Option("en", "--target", help="Target language code."),
    source_lang: str = typer.Option("ja", "--source", help="Source language code."),
    bilingual: bool = typer.Option(
        False, "--bilingual/--replace", help="Include original text on top."
    ),
    speakers: int = typer.Option(
        None,
        "--speakers",
        "-s",
        help="Reserved for future diarization work. Ignored by the current single-speaker pipeline.",
    ),
    keyframes: Path = typer.Option(
        None,
        "--keyframes",
        help="Path to existing keyframes log (overrides extraction).",
    ),
    extract_keyframes: bool = typer.Option(
        True,
        "--extract-keyframes/--no-extract-keyframes",
        help="Automatically extract keyframes when optional external tooling is installed.",
    ),
    chunk: bool = typer.Option(
        False,
        "--chunk/--no-chunk",
        help="Split translation into smaller chunks with retry logic. Useful for long files.",
    ),
    chunk_size: int = typer.Option(
        80,
        "--chunk-size",
        help="Number of subtitle lines per chunk when --chunk is enabled.",
    ),
    start: str = typer.Option(
        None,
        "--start",
        help="Start time for transcription (e.g. 00:01:00 or 60).",
    ),
    end: str = typer.Option(
        None,
        "--end",
        help="End time for transcription (e.g. 00:04:00 or 240).",
    ),
):
    """
    Runs the end-to-end Japanese pipeline (Transcribe -> Format -> Translate -> Postprocess).
    """
    logger.info(f"Starting full autosub pipeline for: {video_path}")

    if not out_dir:
        out_dir = video_path.parent

    out_dir.mkdir(parents=True, exist_ok=True)

    transcript_out = out_dir / "transcript.json"
    original_ass_out = out_dir / "original.ass"
    translated_ass_out = out_dir / "translated.ass"

    # Resolve Profile
    final_vocab = []
    final_prompt_parts = []
    final_timing = {}
    final_extensions = {}
    replacements = {}
    profile_speakers_requested = False
    if profile:
        profile_data = load_unified_profile(profile)
        final_vocab.extend(profile_data["vocab"])
        final_prompt_parts.extend(profile_data["prompt"])
        final_timing = profile_data.get("timing", {})
        final_extensions = profile_data.get("extensions", {})
        replacements = profile_data.get("replacements", {})
        profile_speakers_requested = bool(profile_data.get("speakers"))

        if profile_data.get("glossary"):
            glossary_text = "Glossary (Always translate these exact phrases):\n"
            for ja, en in profile_data["glossary"].items():
                glossary_text += f'- "{ja}" -> "{en}"\n'
            final_prompt_parts.append(glossary_text)

    if vocab:
        final_vocab.extend(vocab)
    if prompt:
        final_prompt_parts.append(prompt)

    if speakers:
        logger.warning(
            "--speakers is currently ignored. The active pipeline is single-speaker only."
        )
    elif profile_speakers_requested:
        logger.warning(
            "Profile speaker settings are currently ignored. The active pipeline is single-speaker only."
        )

    final_prompt = "\n\n".join(final_prompt_parts) if final_prompt_parts else None

    # Step 1: Transcribe
    try:
        logger.info("[Step 1/4] Transcribing...")
        transcribe_main.transcribe(
            video_path,
            transcript_out,
            language,
            final_vocab,
            start_time=start,
            end_time=end,
        )
    except Exception as e:
        logger.error(f"Failed during transcription: {e}")
        raise typer.Exit(code=1)

    # Step 1.5: Keyframes
    kf_ms = None
    vid_duration_ms = None
    try:
        logger.info("[Step 1.5/4] Processing Video Keyframes & Metadata...")
        from autosub.pipeline.video.keyframes import (
            get_fps,
            extract_keyframes as extract_keyframes_func,
            parse_aegisub_keyframes,
        )

        fps = get_fps(video_path)
        if fps > 0:
            import ffmpeg

            probe = ffmpeg.probe(str(video_path))
            try:
                vid_duration_ms = int(float(probe["format"]["duration"]) * 1000)
            except Exception:
                pass

            if keyframes and keyframes.exists():
                logger.info(f"Using provided keyframes: {keyframes}")
                kf_ms = parse_aegisub_keyframes(keyframes, fps)
            elif extract_keyframes:
                kf_out = out_dir / f"{video_path.stem}_keyframes.log"
                logger.info(f"Extracting keyframes to {kf_out}...")
                extract_keyframes_func(video_path, kf_out)
                kf_ms = parse_aegisub_keyframes(kf_out, fps)
        else:
            logger.warning("No video stream found. Keyframe extraction disabled.")
    except Exception as e:
        logger.warning(f"Failed to process keyframes: {e}")

    # Step 2: Format
    try:
        logger.info("[Step 2/4] Formatting...")
        format_module.format_subtitles(
            transcript_out,
            original_ass_out,
            keyframes=kf_ms,
            video_duration_ms=vid_duration_ms,
            timing_config=final_timing,
            extensions_config=final_extensions,
            replacements=replacements,
        )
    except Exception as e:
        logger.error(f"Failed during formatting: {e}")
        raise typer.Exit(code=1)

    # Step 3: Translate
    chunk_size = chunk_size if chunk else 0

    try:
        logger.info("[Step 3/4] Translating...")
        translate_module.translate_subtitles(
            original_ass_out,
            translated_ass_out,
            engine=engine,
            system_prompt=final_prompt,
            target_lang=target_lang,
            source_lang=source_lang,
            bilingual=bilingual,
            chunk_size=chunk_size,
        )
    except Exception as e:
        logger.error(f"Failed during translation: {e}")
        raise typer.Exit(code=1)

    # Step 4: Postprocess
    try:
        logger.info("[Step 4/4] Postprocessing...")
        postprocess_module.postprocess_subtitles(
            translated_ass_out,
            extensions_config=final_extensions,
            bilingual=bilingual,
        )
    except Exception as e:
        logger.error(f"Failed during postprocessing: {e}")
        raise typer.Exit(code=1)

    logger.info(
        f"Pipeline completed successfully! Final output saved to {translated_ass_out}"
    )


if __name__ == "__main__":
    app()
