extends = ["proseka_aftertalk"]

prompt = "prompts/proseka_vbs.md"
vocab = [
    # --- Characters ---
    "小豆沢こはね",
    "白石杏",
    "東雲彰人",
    "青柳冬弥",

    # --- Voice Actors ---
    "秋奈",
    "澄利冴那",
    "今井文也",
    "伊東健人",
]

[glossary]
"小豆沢こはね" = "Kohane Azusawa"
"白石杏" = "An Shiraishi"
"東雲彰人" = "Akito Shinonome"
"青柳冬弥" = "Toya Aoyagi"
